### ISSUE TITLE
Game crashes when going through an immersive portal with the mod

### ISSUE THREAD

**Issue by FIREBALL-Z42** [Virtuoel/Pehkui#71]
my game freezes and crashes whenever I use an enlarged/shrunken portal.

**Comment by FIREBALL-Z42** [comment]
by the mod I mean Pehkui

**Comment by Virtuoel** [comment]
What Pehkui version are you using?

**Comment by FIREBALL-Z42** [comment]
latest

**Comment by FIREBALL-Z42** [comment]
for fabric 1.16

**Comment by FIREBALL-Z42** [comment]
the error message is 
"The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: virtuoel.pehkui.api.ScaleType.getScaleData(Lnet/minecraft/class_1297;)Lvirtuoel/pehkui/api/ScaleData;
Exit Code: -1"

**Comment by Virtuoel** [comment]
The latest version that works with Immersive Portals on 1.16 Fabric is currently 1.10.0.

**Comment by FIREBALL-Z42** [comment]
I can only find up to 2.0.0

**Comment by FIREBALL-Z42** [comment]
wait, sorry about that last one

**Comment by FIREBALL-Z42** [comment]
it still does the same thing

**Comment by Virtuoel** [comment]
Hmm, strange. Can you post the full crash log?

**Comment by FIREBALL-Z42** [comment]
yeah give me a sec

**Comment by FIREBALL-Z42** [comment]
[Crash for github.txt](https://github.com/Virtuoel/Pehkui/files/6300566/Crash.for.github.txt)

**Comment by FIREBALL-Z42** [comment]
here

**Comment by Virtuoel** [comment]
According to that log you're still using Pehkui 1.6.2.

**Comment by FIREBALL-Z42** [comment]
I put it in the wrong folder

**Comment by FIREBALL-Z42** [comment]
it might work now

**Comment by FIREBALL-Z42** [comment]
it worked thank you so much
